[package]
name = "multi_type_task_queue_builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.32"
syn = "2.0.28"
task = { path = "../../../task/Rust/task" }

[lib]
proc-macro = true
