name: Build and test Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd Rust/sharded_queue && cargo build --verbose
    - name: Run tests
      run: cd Rust/sharded_queue && cargo test --verbose
